name: parser_combinator
description: Parser combinator is a collection of parsers that can be used to combine basic parsers to create parsers for more complex rules.
repository: https://github.com/mezoni/parser_combinator
version: 0.2.7
topics:
  - parser
  - parser-combinator
  - parsing
  - peg
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  _fe_analyzer_shared: ^63.0.0
  intl: ^0.18.1
  path: ^1.8.3
dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6